$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: wisconsin-bca
description: Training Pipeline to train a model on the Wisconsin BCa dataset

# <inputs_and_outputs>
inputs:
  input_data:
    type: uri_file
    path: azureml:wisconsin-bca-data@latest #in parquet file

# I think azure automagically fills in these values for the outputs
outputs: 
  train_data:
  val_data:
  test_data:
  trained_model:
  evaluation_output:
  model_info_output_path:
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false

jobs:
  prep_data:
    name: prep_data
    display_name: prep-data
    code: ../../develop
    command: >-
      python prep.py 
      --raw_data ${{inputs.raw_data}} 
      --train_data ${{outputs.train_data}}
      --val_data ${{outputs.val_data}}
      --test_data ${{outputs.test_data}}
    environment: azureml:wisconsin-bca-env@latest
    inputs:
      raw_data: ${{parent.inputs.input_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      val_data: ${{parent.outputs.val_data}}
      test_data: ${{parent.outputs.test_data}}

  train_model:
    name: train_model
    display_name: train-model
    code: ../../develop
    command: >-
      python train.py 
      --train_data ${{inputs.train_data}} 
      --model_output ${{outputs.model_output}}
    environment: azureml:wisconsin-bca-env@latest
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
    outputs:
      model_output: ${{parent.outputs.trained_model}}
  
  evaluate_model:
    name: evaluate_model
    display_name: evaluate-model
    code: ../../develop
    command: >-
      python evaluate.py 
      --model_name ${{inputs.model_name}} 
      --model_input ${{inputs.model_input}} 
      --test_data ${{inputs.test_data}} 
      --evaluation_output ${{outputs.evaluation_output}}
    environment: azureml:wisconsin-bca-env@latest
    inputs:
      model_name: "wisconsin-BCa-model"
      model_input: ${{parent.jobs.train_model.outputs.model_output}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      evaluation_output: ${{parent.outputs.evaluation_output}}

  register_model:
    name: register_model
    display_name: register-model
    code: ../../develop
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --evaluation_output ${{inputs.evaluation_output}}
      --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:wisconsin-bca-env@latest
    inputs:
      model_name: "wisconsin-BCa-model"
      model_path: ${{parent.jobs.train_model.outputs.model_output}}
      evaluation_output: ${{parent.jobs.evaluate_model.outputs.evaluation_output}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}