name: base

# this conda environment.yml file is just for us to locally develop our project
# it should be a superset of the conda environment we train and deploy with!
channels:
  - defaults
dependencies:
  - python=3.11.3
  - pip
  - pip:
      - numpy
      - scikit-learn==1.2.2
      - azureml-mlflow
      - azure-ai-ml
      - mlflow[extras]
      - inference-schema
      - azureml-inference-server-http # needed to run local endpoint
      - azure-cli # used in Github Actions
