name: base
channels:
  - defaults
dependencies:
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - scipy=1.9.1
  - python=3.9.13
  - pip=22.2.2
  - tqdm
  - ipykernel
  - flask>=2.0.0
  - pip:
      - numpy
      - azureml-mlflow
      - mlflow
      - azureml-sdk
      - azureml-widgets
      - azure-ai-ml
