name: base

# this conda environment.yml file is just for us to locally develop our project
# it should be a superset of the conda environment we train and deploy with!
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy
      - seaborn # data science stuff
      - ipykernel # data science stuff
      - scikit-learn==1.2.2
      - azureml-mlflow
      - azure-ai-ml # azure/
      - mlflow[extras] # azure/pipeline
      - inference-schema # azure/deploy/score.py
      - azureml-inference-server-http # needed to run local endpoint i guess?
      - pylint # for development
      - azure-cli # used in Github Actions
      - mldesigner==0.1.0b13 # lib/pipeline
