name: Environment Changed

# Update environment (push changes to Azure if it's a push to main)
# Then run Pipeline to see if everything is working with the new environment

on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - .github/workflows/environment.yml # this file
      - environment.yml # actual conda environment file
      - azure/env/update.py # script to update environment
  pull_request:
    paths:
      - .github/workflows/environment.yml # this file
      - environment.yml # actual conda environment file
      - azure/env/update.py # script to update environment

jobs:
  # this runs train-evaluate-register stuff on the Azure compute instances.
  update-environment:
    runs-on: ubuntu-latest
    env:
      # cache just the env folder, not the entire miniconda directory
      # https://github.com/conda-incubator/setup-miniconda/issues/266
      CONDA_PATH: /usr/share/miniconda/envs/__setup_conda
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Azure and Conda
        uses: ./.github/actions/setup-azure-conda
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # version automatically updates, even if environment.yml doesn't change
      - name: Run Deploy
        # run only if it's a push to main (and not a PR)
        # https://stackoverflow.com/a/66206183
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          PYTHONPATH="lib" python azure/env/update.py
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME }}


  run-pipeline:
    needs: update-environment
    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
