name: Upload New Environment


on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - .github/workflows/environment.yml # this file
      - environment.yml # actual conda environment file
      - azure/azure-env.yml # azureml environment file


jobs:
  # this runs train-evaluate-register stuff on the Azure compute instances.
  update-environment:
    runs-on: ubuntu-latest
    env:
      # cache just the env folder, not the entire miniconda directory
      # https://github.com/conda-incubator/setup-miniconda/issues/266
      CONDA_PATH: /usr/share/miniconda/envs/__setup_conda
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Workspace and RG Defaults
        run: |
          az configure --defaults workspace=${{ vars.AZURE_WORKSPACE_NAME }}
          az configure --defaults group=${{ vars.AZURE_RESOURCE_GROUP }}

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9

      - name: Test Conda Installation
        run: |
          conda --version
          which python
          conda env list

      # https://github.com/s-weigand/setup-conda/issues/3
      - name: Cache Conda Environment
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA_PATH }}
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Install environment.yml
        # https://stackoverflow.com/a/43873901
        run: conda env update -n __setup_conda -f environment.yml --prune
        # https://dev.to/epassaro/caching-anaconda-environments-in-github-actions-5hde
        if: steps.cache.outputs.cache-hit != 'true'

      # version automatically updates, even if environment.yml doesn't change
      - name: Run Deploy
        run: |
          PYTHONPATH="lib" python azure/env/update.py
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME }}


  run-pipeline:
    needs: update-environment
    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
