name: Train Evaluate Register


on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - .github/workflows/pipeline.yml # this file
      - azure/train/pipeline.yml # azureml pipeline file
      - develop/*.py # python files responsible for running the pipeline
      - tests/endpoint/*.py # Python files responsible for testing the endpoint


jobs:
  # this runs train-evaluate-register stuff on the Azure compute instances.
  # basically, az ml job create --file azure/train/pipeline.yml
  azure-pipeline:
    name: Azure Pipeline
    # https://github.com/Azure/mlops-templates/blob/main/.github/workflows/run-pipeline.yml
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      workspace_name: ${{ vars.AZURE_WORKSPACE_NAME }}
      resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
      parameters-file:  azure/train/pipeline.yml
      job-name: test
    secrets:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  test-endpoint:
    name: Test Endpoint
    needs: azure-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
      
      - name: Install environment.yml
        run: conda env update -n base -f environment.yml

      - name: Run Endpoint Test
        run: |
          cd tests/endpoint && python main.py
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME }}
