name: Train Evaluate Register


on: 
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - .github/workflows/pipeline.yml # this file
      - azure/train/pipeline.yml # azureml pipeline file
      - develop/*.py # python files responsible for running the pipeline
      - tests/endpoint/*.py # Python files responsible for testing the endpoint


jobs:
  # this runs train-evaluate-register stuff on the Azure compute instances.
  # basically, az ml job create --file azure/train/pipeline.yml
  azure-pipeline:
    name: Azure Pipeline
    # https://github.com/Azure/mlops-templates/blob/main/.github/workflows/run-pipeline.yml
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      workspace_name: ${{ vars.AZURE_WORKSPACE_NAME }}
      resource_group: ${{ vars.AZURE_RESOURCE_GROUP }}
      parameters-file:  azure/train/pipeline.yml
      job-name: test
    secrets:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  test-endpoint:
    uses: ./.github/workflows/test-endpoint.yml
