name: Conda Endpoint Test

on: [ push ]

jobs:
  test-endpoint:
    name: Test Endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
      
      - name: Test Conda Installation
        run: |
          conda --version
          which python
      
      - name: Install environment.yml
        run: conda env update -n base -f environment.yml

      - name: Run Endpoint Test
        run: |
          cd tests/endpoint && python main.py
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME }}
