name: Endpoint Test

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - .github/workflows/test-endpoint.yml # this file
      - tests/endpoint/* # Files responsible for testing the endpoint
      - lib/*.py # Helper functions 

jobs:
  test-endpoint:
    name: Test Endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Azure and Conda
        uses: ./.github/actions/setup-azure-conda
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Endpoint Test
        run: |
          PYTHONPATH="lib" python tests/endpoint/main.py
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME }}
