name: Test Azure Pipeline (DELETE ME)

on:
  push:
  workflow_dispatch:

jobs:
  azure-pipeline:
    name: Run train/evaluate/register
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Azure and Conda
        uses: ./.github/actions/setup-azure-conda
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Deploy
        run: |
          PYTHONPATH="lib" python azure/pipeline/main.py
        env:
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          WORKSPACE_NAME: ${{ vars.AZURE_WORKSPACE_NAME }}